import json
p='next/data/analysis.json';a=json.load(open(p))
notes={
0:('Algorithms and computational limits','Most entries here come from theoretical computer science. The representative papers ask how quickly a problem can be solved, checked, or simulated. Quantum-computing entries appear nearby because they share the language of algorithms and resource bounds.'),
1:('Randomness and collective behavior','Probability and mathematical physics dominate this group. Its representative papers study models with many interacting parts: individual randomness can produce large-scale patterns or changes of behavior.'),
2:('Counterexamples and the limits of conjectures','This group crosses many subjects. Its representative entries construct objects claimed to violate an expected rule. That is a shared kind of conclusion, not evidence that the constructions use the same proof.'),
3:('Patterns in numbers and discrete structures','Combinatorics and number theory are prominent here. The representative questions concern patterns that must occur, how numbers factor, and how a graph can be decomposed. The commonality is discrete structure, not one universal method.'),
4:('Geometry, bounds, and regularity','Geometry, analysis, and differential equations meet here. Representative results concern shape, curvature, sharp bounds, or places where a geometric object fails to be smooth. These subjects share analytical tools, but the embedding alone does not identify a particular shared argument.'),
5:('Algebraic structure and arithmetic geometry','This broad group includes algebraic geometry, number theory, groups, topology, and operator algebras. Its central entries concern how rich mathematical structures can be described or related. The breadth of the group is a reason to inspect local neighbors, not to treat it as one topic.')}
for c in a['clusters']:c['label'],c['interpretation']=notes[c['id']]
pairs={
('196','249'):('Both entries construct unusual groups to challenge established conjectures. The shared vocabulary of groups and classifying spaces helps explain why they are close.','Their conclusions differ sharply: family 196 claims a group with a two-dimensional classifying space and problematic group-algebra multiplication; family 249 claims a group for which no two-dimensional classifying space exists. Nearby does not mean the same object or theorem.'),
('073','166'):('Both questions ask how many distances a set of points can determine. They connect geometric structure with quantitative information about distance.','Family 073 concerns possibly fractal compact sets and the measure of their distance sets. Family 166 concerns a finite collection of points and a lower bound on the number of distinct distances. Continuous size and finite counting are different notions.'),
('197','285'):('Both involve torsion-free groups and algebraic structures built from them, and both report counterexamples to conjectures.','Family 197 studies group algebras over a finite field and one-sided inverses. Family 285 studies reduced group C*-algebras and assembly maps. The coefficient system, mathematical setting, and failed properties differ.'),
('051','338'):('Both concern complex geometric spaces called Kähler manifolds and seek strong structural conclusions from geometric restrictions.','Family 051 concerns compact spaces with a restriction on entire curves. Family 338 concerns complete noncompact spaces with positive curvature. Their assumptions are different, and one should not apply either conclusion outside its stated setting.')}
for pair in a['crossSubjectPairs']:
 if (pair['a'],pair['b']) in pairs:pair['similar'],pair['different']=pairs[(pair['a'],pair['b'])]
a['summary']='The six reading groups are weakly separated (cosine silhouette about 0.09). Several groups align with subjects, while the counterexample group cuts across subjects because of the kind of result claimed. Local comparisons are more informative than interpreting every visual island as a mathematical field.'
json.dump(a,open(p,'w'),indent=2)
