import {assetUrl,siteConfig} from './site.js';
// Basic consent mode: no Google tag or event queue before explicit opt-in.
const consentKey='math-explorer:analytics-consent:v1',maxAge=180*24*60*60*1000;
let config=null,ready=false,allowed=false,currentPage=null,lastSent='';
const cleanReferrer=()=>{try{return new URL(document.referrer).origin+'/';}catch{return '';}};
function preference(){try{const p=JSON.parse(localStorage.getItem(consentKey));return p&&p.version===1&&Date.now()-p.at<maxAge?p.choice:null;}catch{return null;}}
function clearCookies(){for(const raw of document.cookie.split(';')){const name=raw.trim().split('=')[0];if(!/^(_ga($|_)|_gid$|_gat($|_))/.test(name))continue;const parts=location.hostname.split('.');document.cookie=`${name}=; Max-Age=0; Path=/; SameSite=Lax`;for(let i=0;i<parts.length-1;i++)for(const domain of [parts.slice(i).join('.'),'.'+parts.slice(i).join('.')])document.cookie=`${name}=; Max-Age=0; Path=/; Domain=${domain}; SameSite=Lax`;}}
function canEnable(){return config?.enabled===true&&config?.privacyReady===true&&config?.operatorName&&config?.contactEmail&&/^G-[A-Z0-9]{6,20}$/.test(config.measurementId||'');}
function sendPage(){if(!ready||!allowed||!currentPage||lastSent===currentPage.key)return;lastSent=currentPage.key;window.gtag('event','explorer_view',currentPage.data);}
export function trackPage(state){const views=['map','library','subjects','reader','insights'];if(!views.includes(state.view))return;const family=state.view==='reader'&&/^\d{3}$/.test(state.family||'')?state.family:'';const path=location.origin+location.pathname+'#view='+state.view+(family?'&family='+family:'');currentPage={key:path,data:{view:state.view,...(family?{family_id:family}:{}),page_location:path}};sendPage();}
const fields={eli5_toggle:['enabled'],subject_filter:['subject'],concept_lens:['lens','corpus','dimensions'],pdf_download:['family_id']};
export function trackEvent(name,params={}){if(!ready||!allowed||!fields[name])return;const safe={};for(const field of fields[name])if(['string','number','boolean'].includes(typeof params[field]))safe[field]=typeof params[field]==='string'?params[field].slice(0,100):params[field];window.gtag('event',name,safe);}
function enable(){if(!canEnable()||ready)return;allowed=true;window['ga-disable-'+config.measurementId]=false;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag('consent','default',{analytics_storage:'granted',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});window.gtag('js',new Date());window.gtag('config',config.measurementId,{send_page_view:true,allow_google_signals:false,allow_ad_personalization_signals:false,cookie_expires:15552000,cookie_update:false,page_location:location.origin+location.pathname,page_referrer:cleanReferrer()});const script=document.createElement('script');script.async=true;script.id='analytics-tag';script.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(config.measurementId);document.head.append(script);ready=true;sendPage();}
function choose(choice){try{localStorage.setItem(consentKey,JSON.stringify({version:1,choice,at:Date.now()}));}catch{}document.querySelector('#analytics-consent')?.remove();document.querySelector('#privacy-dialog')?.close();document.querySelector('#privacy-dialog')?.remove();if(choice==='accepted'){enable();return;}allowed=false;if(config?.measurementId)window['ga-disable-'+config.measurementId]=true;clearCookies();if(ready)location.reload();}
function controls(parent){const actions=document.createElement('div');actions.className='privacy-actions';for(const [label,choice] of [['Reject analytics','rejected'],['Accept analytics','accepted']]){const b=document.createElement('button');b.type='button';b.className='btn';b.textContent=label;b.onclick=()=>choose(choice);actions.append(b);}parent.append(actions);}
function showPrivacy(){let dialog=document.querySelector('#privacy-dialog');if(dialog){dialog.showModal();return;}dialog=document.createElement('dialog');dialog.id='privacy-dialog';dialog.setAttribute('aria-labelledby','privacy-title');dialog.innerHTML=`<h2 id="privacy-title">Privacy settings</h2><p id="analytics-status"></p><h3>Page counts</h3><p>${siteConfig.hosting==='github-pages'?'This frontend is hosted by GitHub Pages. GB10 page counts do not measure visits here. GitHub processes connection information for hosting and security.':'The GB10 server keeps daily totals of app and demo page requests for 90 days. This counter uses no cookies or browser tracking code and stores no IP addresses, visitor identifiers, URLs, referrers or search text. Reloads and bots can increase the totals; it does not identify unique visitors.'}</p><h3>Using the explorer</h3><p>${siteConfig.hosting==='github-pages'?'The frontend is hosted on GitHub Pages.':'The app runs on GB10 behind Cloudflare.'} ${siteConfig.backendBase||siteConfig.hosting!=='github-pages'?'Semantic searches and custom concepts pass through Cloudflare to GB10 for embedding.':'This deployment has no custom embedding backend configured.'} The app does not write their text to disk. Hashes and embedding results are cached in memory, up to 256 entries.</p><p>Cloudflare handles connection data such as IP addresses. Paper PDFs are loaded from GitHub when opened. Display fonts are served locally or supplied by your device.</p><h3>Optional analytics</h3><p>If enabled and you accept, Google Analytics receives usage events, page locations, browser/device information and analytics identifiers stored in cookies. Google also receives network information when its script is loaded. Search text and custom concepts are excluded from the app's analytics events. Advertising personalization and Google Signals are disabled.</p><p>You can reject analytics and use every feature. Your choice and ELI5 setting are stored in this browser. The analytics choice expires after 180 days. You can change it here; turning analytics off reloads the page and clears this site's Google Analytics cookies.</p><p><a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google privacy information</a> · <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Cloudflare privacy information</a></p><p id="privacy-contact"></p>`;
 dialog.querySelector('#analytics-status').textContent=canEnable()?(allowed?'Analytics is on for this browser.':'Analytics is off unless you accept.'):'Analytics is paused for all new and reloaded visits. The operator notice and account settings are still being completed.';
 const contact=dialog.querySelector('#privacy-contact');contact.textContent=config?.operatorName&&config?.contactEmail?`Operator: ${config.operatorName}. Privacy contact: ${config.contactEmail}.`:'This technical summary is not a completed privacy notice. Operator contact details have not yet been published.';
 if(canEnable())controls(dialog);const close=document.createElement('button');close.className='btn';close.textContent='Close';close.onclick=()=>{dialog.close();dialog.remove()};dialog.append(close);document.body.append(dialog);dialog.showModal();}
function attachPrivacy(){const nav=document.querySelector('nav');if(!nav||document.querySelector('#privacy-settings'))return;const b=document.createElement('button');b.id='privacy-settings';b.textContent='Privacy';b.type='button';b.onclick=showPrivacy;nav.append(b);}
export async function initAnalytics(){
 try{const response=await fetch(assetUrl('/analytics-config.json'),{cache:'no-store'});if(!response.ok)throw Error();config=await response.json();attachPrivacy();if(!canEnable()){if(config?.measurementId)window['ga-disable-'+config.measurementId]=true;clearCookies();return;}const choice=preference();if(choice==='accepted'){enable();return;}clearCookies();if(choice==='rejected')return;const box=document.createElement('section');box.id='analytics-consent';box.setAttribute('aria-label','Optional analytics');box.innerHTML='<strong>Allow usage analytics?</strong><p>Google Analytics helps us count visits and feature usage. It uses cookies. Search text and custom concepts are not sent. The explorer works without it.</p>';controls(box);const more=document.createElement('button');more.className='inline-link';more.textContent='Privacy details';more.onclick=showPrivacy;box.append(more);document.body.append(box);}catch{allowed=false;clearCookies();attachPrivacy();}
}
