import renderMath from 'katex/contrib/auto-render';
import {initTheme} from '../../src/theme.js';
import {lexicalSearch,semanticSearch,combineSearch,shouldSearchSemantic} from '../../src/search.mjs';
import {siteConfig} from '../../src/site.js';
initTheme();
if(/^https:\/\/github\.com\//.test(siteConfig.repositoryUrl)){const link=document.querySelector('#project-repo');link.href=siteConfig.repositoryUrl;link.hidden=false;}
const $=s=>document.querySelector(s),canvas=$('#map'),stage=$('#stage'),ctx=canvas.getContext('2d');
const palette=['#61d9b6','#76b5f0','#edb465','#b5a3ef','#f091a2','#92c9d2','#cad37a','#e5abdf','#8bdec9','#89a4e4','#ec9b78','#baceed','#d4af84','#a4ca9a','#c498c9','#88c8ee','#e6d995'];
const data=await fetch('./map-data.json?v=20261007c').then(r=>{if(!r.ok)throw Error('Map data unavailable');return r.json()}).catch(e=>{$('#loading').textContent=e.message;throw e});$('#loading').hidden=true;
let recording=false;
const selectedIds=new Set();
let mode='none',selected=null,subject='',hover=null,detailsOpen=false,matched=null,coords=data.modes.none.points.map(p=>[...p]),animation=null,width=stage.clientWidth,height=stage.clientHeight,eli5=true,frame=0,searchToken=0,searchTimer,searchController;
try{eli5=localStorage.getItem('math-explorer:eli5')!=='false'}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,docs=data.docs,byId=new Map(docs.map((d,i)=>[d.id,{...d,index:i}]));
const light=()=>document.documentElement.dataset.theme==='light';
function color(d){const c=palette[data.subjects.indexOf(d.subject)];return light()?'#'+c.slice(1).match(/../g).map(v=>Math.round(parseInt(v,16)*.56).toString(16).padStart(2,'0')).join(''):c;}
const all=Object.values(data.modes).flatMap(m=>m.points),xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),bounds={mx:Math.max(...xs),nx:Math.min(...xs),my:Math.max(...ys),ny:Math.min(...ys)};
const pointPositions=()=>{const{mx,nx,my,ny}=bounds,scale=Math.min((width-65)/(mx-nx),(height-70)/(my-ny));return coords.map(([x,y])=>[width/2+(x-(mx+nx)/2)*scale,height/2+(y-(my+ny)/2)*scale]);};let positions=pointPositions();
const near=()=>selected?data.modes[mode].neighbors[byId.get(selected).index]:[];
const short={'Probability and statistical mechanics':'Probability','Algebraic and complex geometry':'Algebraic geometry','Partial differential equations':'PDEs','Theoretical computer science':'Computer science'};
let labelSignature='';
function labels(){const signature=[width,height,mode,subject,light(),!!selected,!!animation,!!matched].join('|');if(signature===labelSignature)return;labelSignature=signature;const root=$('#labels');root.replaceChildren();if(selected||animation||matched)return;const boxes=[];for(const s of ['Number theory','Combinatorics','Algebraic and complex geometry','Topology','Probability and statistical mechanics','Functional analysis']){const ps=docs.map((d,i)=>d.subject===s?positions[i]:null).filter(Boolean);if(!ps.length)continue;const median=j=>ps.map(p=>p[j]).sort((a,b)=>a-b)[Math.floor(ps.length/2)],title=short[s]||s;ctx.font=(width<700?'9':'11')+'px system-ui';const w=Math.ceil(ctx.measureText(title).width)+16,h=width<700?26:30,cx=median(0),cy=median(1);let best=null;for(let k=0;k<650;k++){const angle=k*2.399963,r=12*Math.sqrt(k),x=Math.max(4,Math.min(width-w-4,cx+Math.cos(angle)*r-w/2)),y=Math.max(4,Math.min(height-h-24,cy+Math.sin(angle)*r-h/2));const overlap=positions.filter(p=>p[0]>x-9&&p[0]<x+w+9&&p[1]>y-9&&p[1]<y+h+9).length;const collisions=boxes.filter(b=>x<b.x+b.w+5&&x+w+5>b.x&&y<b.y+b.h+5&&y+h+5>b.y).length;const score=overlap*1000+collisions*1000+r;if(!best||score<best.score)best={x,y,w,h,score};if(!overlap&&!collisions)break;}if(best.score>=1000)continue;boxes.push(best);const b=document.createElement('button');b.className='map-label';b.textContent=title;b.style.cssText=`left:${best.x}px;top:${best.y}px;width:${w}px;height:${h}px;color:${color({subject:s})};opacity:${subject&&subject!==s?.2:1}`;b.setAttribute('aria-pressed',String(subject===s));b.onclick=()=>filterSubject(s);root.append(b);}}
function draw(now=performance.now()){cancelAnimationFrame(frame);if(animation){const t=Math.min(1,(now-animation.start)/animation.duration),e=t*t*(3-2*t);coords=animation.from.map((p,i)=>p.map((v,j)=>v+(animation.to[i][j]-v)*e));if(t===1)animation=null;}
 positions=pointPositions();ctx.clearRect(0,0,width,height);const neighbors=matched?[]:near(),ids=new Set(neighbors.map(n=>n.id)),active=!matched&&selected&&byId.get(selected),filter=subject||(hover&&!selected&&byId.get(hover).subject);
 if(active){const[x,y]=positions[active.index];for(const n of neighbors){const[a,b]=positions[byId.get(n.id).index];ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(a,b);ctx.strokeStyle=light()?'#416f7e70':n.id===neighbors[0]?.id?'#b3e5ddaa':'#8ca6b050';ctx.lineWidth=n.id===neighbors[0]?.id?1.5:1;ctx.stroke();}}
 docs.forEach((d,i)=>{const[x,y]=positions[i],chosen=!matched&&selectedIds.has(d.id),close=ids.has(d.id),dim=(!matched&&selected&&!chosen&&!close)||(filter&&d.subject!==filter)||(matched&&!matched.has(d.id));ctx.globalAlpha=dim?(recording?.55:.1):chosen?1:close?(recording?.8:.48):.87;const r=chosen?9:close?5:width<700?3.7:5.4;ctx.fillStyle=color(d);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(chosen){ctx.globalAlpha=1;ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.strokeStyle=light()?'#285846':'#d8fff0';ctx.lineWidth=1.3;ctx.stroke();}});ctx.globalAlpha=1;
 if(active){const[x,y]=positions[active.index];ctx.font='500 12px system-ui';ctx.fillStyle=light()?'#294839':'#d1e9e2';ctx.fillText('Family '+active.id,Math.max(5,x-95),y-23);const first=neighbors[0]&&byId.get(neighbors[0].id);if(first){const[a,b]=positions[first.index];ctx.fillStyle=light()?'#506b7a':'#a6bfcc';ctx.font='11px system-ui';ctx.fillText('Closest · '+first.id,Math.min(width-95,a+20),b+22);}}
 if(animation)frame=requestAnimationFrame(draw);else labels();}
function resize(){width=stage.clientWidth;height=stage.clientHeight;const dpr=Math.min(devicePixelRatio,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()};new ResizeObserver(resize).observe(stage);addEventListener('themechange',()=>{draw();updateSubjects()});
function setMode(next){closePopover();hover=null;if(next===mode)return;mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));animation={from:coords.map(p=>[...p]),to:data.modes[mode].points,start:performance.now(),duration:reduced?1:650};labelSignature='';$('#labels').replaceChildren();renderCard();draw();}
function cancelSearch(){clearTimeout(searchTimer);searchController?.abort();searchToken++;}
function select(id,additive=false){if(additive&&!id)return;if(additive){if(selectedIds.has(id))selectedIds.delete(id);else selectedIds.add(id);id=selectedIds.has(id)?id:[...selectedIds].at(-1)||null;}else{selectedIds.clear();if(id)selectedIds.add(id);}cancelSearch();$('#find').value='';$('#clear-search').hidden=true;selected=id;subject='';hover=null;matched=null;$('#hover-title').textContent='';closePopover();$('#search-status').textContent='';if(!selected)detailsOpen=false;renderCard();updateSubjects();draw();const h=new URLSearchParams();if(id)h.set('family',id);if(selectedIds.size>1)h.set('selected',[...selectedIds].join(','));history.replaceState(null,'',h.size?'#'+h:location.pathname);}
const math=el=>renderMath(el,{delimiters:[{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false}],throwOnError:false,trust:false});
function renderCard(){const d=selected&&byId.get(selected);$('#selection').hidden=!d;$('#card').hidden=!d||!detailsOpen;$('#workspace').classList.toggle('details-open',!!d&&detailsOpen);$('#details-toggle').setAttribute('aria-expanded',String(detailsOpen));$('#details-toggle').textContent=detailsOpen?'Hide details':'Details';if(!d)return;$('#selection-meta').textContent=(selectedIds.size>1?selectedIds.size+' selected · ':'')+d.subject+' · Family '+d.id;$('#selection-title').textContent=d.title;$('#card-meta').textContent=d.subject+' / '+d.id;$('#card-title').textContent=d.title;math($('#card-title'));math($('#selection-title'));const generic=d.question==='What is this entry trying to establish?'||!d.idea||d.idea.includes('This entry studies the specific objects');$('#guide-label').textContent=eli5&&generic?'Original claim · plain-language guide not yet available':eli5?'Plain-language guide':'Original claim';$('#card-question').textContent=eli5&&!generic?d.question:'';$('#card-idea').textContent=eli5&&!generic?d.idea:d.summary;$('#card-question').hidden=!$('#card-question').textContent;math($('#card-idea'));$('#eli5').setAttribute('aria-checked',String(eli5));$('#read').href='../#view=reader&family='+d.id;$('#related').replaceChildren();const title=document.createElement('small');title.textContent='Nearest by '+({none:'all features',topics:'topics',methods:'proof techniques'}[mode]);$('#related').append(title);for(const n of near()){const b=document.createElement('button');b.textContent=n.id+' · '+byId.get(n.id).title;b.onclick=e=>select(n.id,e.shiftKey);$('#related').append(b);math(b);}}
function updateSubjects(){document.querySelectorAll('[data-subject]').forEach(b=>{b.style.opacity=subject&&b.dataset.subject!==subject?'.25':'1';b.setAttribute('aria-pressed',String(b.dataset.subject===subject));b.querySelector('b').style.background=color({subject:b.dataset.subject})});}
function filterSubject(s){const next=subject===s?'':s;select(null);subject=next;matched=null;updateSubjects();draw()}
for(const s of data.subjects){const b=document.createElement('button');b.dataset.subject=s;b.setAttribute('aria-pressed','false');const swatch=document.createElement('b');swatch.style.background=color({subject:s});b.append(swatch,document.createTextNode(short[s]||s));b.onclick=()=>{const next=subject===s?'':s;select(null);subject=next;updateSubjects();draw()};$('#subjects').append(b);}
const hit=(x,y)=>{let found=null,best=matchMedia('(pointer: coarse)').matches?22:16;positions.forEach((p,i)=>{const d=Math.hypot(x-p[0],y-p[1]);if(d<best){best=d;found=docs[i].id}});return found};
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=canvas.getBoundingClientRect(),id=hit(e.clientX-rect.left,e.clientY-rect.top);if(id===hover)return;hover=id;canvas.style.cursor=id?'pointer':'default';$('#hover-title').textContent=id?byId.get(id).title:'';draw()});canvas.addEventListener('pointerleave',()=>{hover=null;$('#hover-title').textContent='';draw()});let press=null;
canvas.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;press={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointerup',e=>{if(!press||press.id!==e.pointerId)return;const start=press;press=null;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>10)return;const r=canvas.getBoundingClientRect(),id=hit(e.clientX-r.left,e.clientY-r.top);select(!e.shiftKey&&selectedIds.size===1&&id===selected?null:id,e.shiftKey);e.preventDefault()});
canvas.addEventListener('pointercancel',()=>{press=null});

$('#details-toggle').onclick=()=>{detailsOpen=!detailsOpen;renderCard()};$('#close').onclick=()=>{detailsOpen=false;renderCard()};$('#clear-selection').onclick=()=>select(null);$('#reset').onclick=()=>{clearSearch();select(null);subject='';setMode('none');updateSubjects()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#eli5').onclick=()=>{eli5=!eli5;try{localStorage.setItem('math-explorer:eli5',String(eli5))}catch{}renderCard()};
function closePopover(){$('#search-popover').hidden=true;$('#find').setAttribute('aria-expanded','false');}
function showResults(matches,q,extra=''){const root=$('#results');root.replaceChildren();root.hidden=!q;$('#search-popover').hidden=!q;$('#find').setAttribute('aria-expanded',String(!!q));matched=q?new Set(matches.map(f=>f.id)):null;$('#search-status').textContent=q?`${matches.length} matching families${extra}`:'';for(const d of matches){const b=document.createElement('button'),id=document.createElement('span'),body=document.createElement('span'),meta=document.createElement('small');b.type='button';id.className='result-id';id.textContent=d.id;body.textContent=d.title;meta.textContent=d.subject+(d.lean?' · Lean linked':'');body.append(meta);b.append(id,body);b.onclick=e=>select(d.id,e.shiftKey);root.append(b);math(body)}draw()}
async function runSemantic(q,token){if(!shouldSearchSemantic(q))return;searchController=new AbortController();try{const related=await semanticSearch(docs,q,searchController.signal);if(token!==searchToken)return;showResults(combineSearch(docs,q,related),q,' · text matches first, then related results')}catch(e){if(token===searchToken&&e.name!=='AbortError')$('#search-status').textContent+= ' · semantic search unavailable; showing text matches'}}
function search(immediate=false){cancelSearch();const q=$('#find').value.trim(),token=searchToken;subject='';updateSubjects();$('#clear-search').hidden=!q;showResults(lexicalSearch(docs,q),q);if(q)searchTimer=setTimeout(()=>runSemantic(q,token),immediate?0:1100)}
function clearSearch(){cancelSearch();$('#find').value='';$('#clear-search').hidden=true;matched=null;closePopover();$('#search-status').textContent='';draw()}
document.addEventListener('pointerdown',e=>{if(!$('#search-form').contains(e.target)){closePopover();cancelSearch();}});
$('#find').addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&!$('#search-popover').hidden){e.preventDefault();$('#results button')?.focus()}});
$('#find').oninput=()=>search();$('#find').onfocus=()=>{if($('#find').value.trim())search()};$('#search-form').onsubmit=e=>{e.preventDefault();search(true)};$('#clear-search').onclick=clearSearch;addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#search-popover').hidden){closePopover();cancelSearch()}else{detailsOpen=false;renderCard()}}});
window.explorer={get mode(){return mode},get selected(){return selected},get selectedIds(){return [...selectedIds]},point:id=>{const r=canvas.getBoundingClientRect(),p=positions[byId.get(id).index];return[p[0]+r.left,p[1]+r.top]},get animating(){return!!animation},neighbors:()=>near().map(n=>n.id),recording:()=>{recording=true;document.body.classList.add('recording');draw();document.addEventListener('pointermove',e=>{const c=$('#demo-cursor');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'})}};
const params=new URLSearchParams(location.hash.slice(1));if(byId.has(params.get('family'))){const ids=(params.get('selected')||'').split(',').filter(id=>byId.has(id));select(params.get('family'));for(const id of ids)selectedIds.add(id);if(ids.length)history.replaceState(null,'','#'+params);renderCard();}else if(data.subjects.includes(params.get('subject'))){subject=params.get('subject');updateSubjects()}resize();
