import {palette,paperPalette} from './palette.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const modeNames={none:'Titles and abstracts',topics:'Mathematical topics',lean:'Linked Lean source',references:'Shared references'};
export function posterSVG(data,mode='none',light=false){
 const bg=light?'#f4f0e7':'#0b141b',ink=light?'#253b40':'#e2e9e5',muted=light?'#627274':'#91a7ad',line=light?'#c7cec4':'#30434b',colors=light?paperPalette:palette;
 const docs=data.docs.map((d,i)=>({...d,index:i})).filter(d=>mode!=='lean'||data.modes.lean.counts[d.index]>0),coords=docs.map(d=>data.modes[mode].points[d.index]),xs=coords.map(p=>p[0]),ys=coords.map(p=>p[1]),nx=Math.min(...xs),mx=Math.max(...xs),ny=Math.min(...ys),my=Math.max(...ys),scale=Math.min(2000/(mx-nx),1570/(my-ny)),points=coords.map(([x,y])=>[1200+(x-(mx+nx)/2)*scale,1480+(y-(my+ny)/2)*scale]);
 const text=(s,x,y,size=30,fill=ink,extra='')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${fill}" ${extra}>${esc(s)}</text>`;
 let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="2400" height="3000" viewBox="0 0 2400 3000" role="img"><title>OpenAI Mathematics — ${modeNames[mode]}</title><desc>Each point represents one research family, colored by subject. UMAP positions are approximate. ${docs.length} families shown. Independent visualization of openai/math.</desc><rect width="2400" height="3000" fill="${bg}"/><g font-family="Arial, Helvetica, sans-serif">`;
 svg+=text('OPENAI / MATH',150,150,28,muted,'letter-spacing="6"')+text('Mathematics',140,340,178,ink,'font-family="Georgia, Times New Roman, serif"')+text('A map of the research collection',150,427,40,muted);
 svg+=text(String(docs.length).padStart(3,'0'),1790,230,83,ink)+text('RESEARCH FAMILIES',1795,278,22,muted,'letter-spacing="2"')+text(modeNames[mode],1795,354,31,ink)+text('UMAP · 2 dimensions',1795,400,25,muted);
 svg+=`<path d="M150 493H2250" stroke="${line}" stroke-width="2"/>`;
 svg+=text(mode==='lean'?'Named Lean targets + two static reference hops · partial coverage':'372 research families · 722 manuscripts · 17 subjects',150,553,25,muted);
 points.forEach(([x,y],i)=>{svg+=`<circle cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="8.3" fill="${colors[data.subjects.indexOf(docs[i].subject)]}" stroke="${bg}" stroke-width="2"/>`;});
 const names={'Number theory':'Number theory','Algebraic and complex geometry':'Algebraic geometry','Probability and statistical mechanics':'Probability','Combinatorics':'Combinatorics','Topology':'Topology','Functional analysis':'Functional analysis'};const boxes=[];
 for(const [subject,title] of Object.entries(names)){const ps=points.filter((_,i)=>docs[i].subject===subject);if(!ps.length)continue;const median=j=>ps.map(p=>p[j]).sort((a,b)=>a-b)[Math.floor(ps.length/2)],cx=median(0),cy=median(1),w=title.length*16+34,h=44;let best;
 for(let k=0;k<900;k++){let r=16*Math.sqrt(k),angle=k*2.399963,x=Math.max(145,Math.min(2250-w,cx+Math.cos(angle)*r-w/2)),y=Math.max(630,Math.min(2290-h,cy+Math.sin(angle)*r-h/2));let hits=points.filter(p=>p[0]>x-12&&p[0]<x+w+12&&p[1]>y-12&&p[1]<y+h+12).length+boxes.filter(b=>x<b.x+b.w+15&&x+w+15>b.x&&y<b.y+b.h+15&&y+h+15>b.y).length;let score=hits*10000+r;if(!best||score<best.score)best={x,y,w,h,score};if(!hits)break;}
 if(best.score>=10000)continue;boxes.push(best);svg+=`<rect x="${best.x}" y="${best.y}" width="${w}" height="${h}" rx="7" fill="${bg}" fill-opacity=".93"/>`+text(title,best.x+17,best.y+32,29,colors[data.subjects.indexOf(subject)]);
 }
 if(mode==='references')svg+=text(data.modes.references.isolated.length+' families without matched shared references are shown in the bottom row.',150,2345,23,muted);
 svg+=`<path d="M150 2390H2250" stroke="${line}" stroke-width="2"/>`;
 data.subjects.forEach((s,i)=>{const col=i%3,row=Math.floor(i/3),x=150+col*710,y=2470+row*55;svg+=`<circle cx="${x+8}" cy="${y-9}" r="6" fill="${colors[i]}"/>`+text(s==='Probability and statistical mechanics'?'Probability & statistical mechanics':s,x+30,y,24,muted);});
 svg+=text('Each dot is a research family. Nearby points tend to be more similar; distances are approximate.',150,2845,23,muted)+text('Independent visualization · Source: openai/math · Snapshot '+data.commit.slice(0,7),150,2890,22,muted)+text('dylanwootton.com/openai-math-explorer',150,2935,22,ink);
 return svg+'</g></svg>';
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function openPoster(data,mode,light){let dialog=document.querySelector('#poster-dialog');dialog?.remove();dialog=document.createElement('dialog');dialog.id='poster-dialog';dialog.setAttribute('aria-label','Download map poster');const svg=posterSVG(data,mode,light),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));dialog.innerHTML='<div class="poster-heading"><h2>Map poster</h2><button aria-label="Close poster">×</button></div><img alt="Preview of the current comparison as a map poster"><div class="poster-actions"><button data-format="svg">Download SVG</button><button data-format="png">Download PNG</button></div><p>Full map · current theme · SVG scales to any print size</p><p role="status" class="poster-status"></p>';dialog.querySelector('img').src=url;document.body.append(dialog);dialog.querySelector('[aria-label="Close poster"]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{URL.revokeObjectURL(url);dialog.remove()},{once:true});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.querySelector('[data-format="svg"]').onclick=()=>download(new Blob([svg],{type:'image/svg+xml'}),'openai-math-'+mode+'.svg');dialog.querySelector('[data-format="png"]').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=3000;canvas.getContext('2d').drawImage(img,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('Image encoding failed');download(blob,'openai-math-'+mode+'.png');}catch{dialog.querySelector('.poster-status').textContent='PNG could not be created. You can still download the SVG.';}finally{button.disabled=false;}};dialog.showModal();
}
